### ISSUE TITLE
Support for urllib3 >= 2.2.1

### ISSUE THREAD

**Issue by NickBoyett** [Bandwidth/python-sdk#185]
Long time no dependency update requests. Hope you are all doing well!

Hoping to resolve the following:

`bandwidth-sdk 15.1.0 requires urllib3<2.1.0,>=1.25.3, but you have urllib3 2.2.1 which is incompatible.`

**Comment by ajrice6713** [comment]
Hey @NickBoyett! 

Likewise! 

Should be able to get this resolved - just FYI `>=v15.0.0` of this library is generated with the [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) project. 

For dependencies specifically we ignore those and override, so this is an easy fix on our end that Ill get updated today - but if you have other feature requests (which are always welcome!) we may need to contribute back to the parent, which  could take a little longer depending on their release cycle.
