### ISSUE TITLE
Support for pydantic >= 2.6.4

### ISSUE THREAD

**Issue by NickBoyett** [Bandwidth/python-sdk#186]
`bandwidth-sdk 15.1.0 requires pydantic<2,>=1.10.5, but you have pydantic 2.6.4 which is incompatible.`

**Comment by ajrice6713** [comment]
Hey @NickBoyett - this will be available tomorrow in v16.0.0

Note that there was a small breaking change when using the Media API - the upload media model now requires a strict `bytes` or `string` type, a `bytearray` is no longer allowed. We will have a migration guide available on `dev.bandwidth.com`
